### ISSUE TITLE
JetEngine and JPlugin Automated Testing

### ISSUE THREAD

**Issue by UberPilot** [jet-suite/JetEngine#14]
These two behemoths are what make up most of this plugin and make it easy to use, but they are not tested. 100% coverage is the goal, but it is understood that it may not be met due to the nature of Spigot/Bukkit APIs.
_____
#### Initialization
- [ ] All utilities are created
- [ ] Any unset values fail gracefully or throw exceptions
#### Defaults
- [ ] Core messages are initialized
- [ ] Commands can be toggled or removed
#### File Handling
- [ ] Messages can be overwritten

_____
#### Commands
- [ ] Make sure commands are initialized.
- [ ] Test that all commands follow correct lineage and fail gracefully.
#### Messages
- [ ] Make sure that all needed messages are set.
- [ ] Test overwriting messages on the plugin-level.

**Comment by hhenrichsen** [comment]
Closing because with further experimentation, this does not seem to be doable or show up on coverage reports.
